# Generated by Django 2.1.7 on 2019-06-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190605_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='thumbnail',
            new_name='image_url',
        ),
    ]
