# Generated by Django 2.1.7 on 2019-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190606_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(error_messages={'unique': '优先级已存在,请重新赋值！'}, unique=True),
        ),
    ]
